### ISSUE TITLE
Change project identifier

### ISSUE THREAD

**Issue by gbalcewicz** [uc-group/bear-it#21]
Change project id format to be defined by user (only on creation). Like it is for example in JIRA so the project (i.e PROJECT) related references can be generated like PROJECT-1. While creating ProjectId, validate if it contains proper characters: Starts with letter, contains only uppercase letters and numbers, maximum length 20 characters.

Adjust changes also in database entity.

**Comment by mariuszniemiec** [comment]
Do we want to let user edit current id used in relations? Maybe we could leave this id and create dedicated `identifier` for that purpose? On the other hand, than we will have semi-duplicated field.
Since I'm a bit off from current standards - what is better practice in your opinion?

**Comment by gbalcewicz** [comment]
I think there is no need to have id and identifier. Now the id is generated uuid4 for this. As the project identifier must be unique and it identifies the entity it seems like a candidate for the id. The id must be specified only on project creation. No editing on this value.

**Comment by mariuszniemiec** [comment]
ok I agree. I also missed the "only on creation" remark. This makes me sure even more.
