### ISSUE TITLE
Remove project

### ISSUE THREAD

**Issue by gbalcewicz** [uc-group/bear-it#22]
Add possibility to remove project. Extend ProjectRepositoryInterface to enforce remove(ProjectId) method.

**Comment by mariuszniemiec** [comment]
Do we want to think more about some constraints here? Or is it ok to go now with project (and issues ) removal with simple "are you sure" prompt?
I think we can leave further complications for further stages or bear-it.
What do you think?

**Comment by gbalcewicz** [comment]
Yes I first thought about archiving. But let's not over complicate it for now. Later the best approach would be IMHO archiving it to some format and deleting it from the database. So we wouldn't keep "trash" but have the possibility to restore it, maybe with different project ID. If it will be sitting in the db as archived there will always be "this value is used but yeah, it's not found" ;).

**Comment by mariuszniemiec** [comment]
Hi @atokarczyk 
I noticed this was probably merged and done in  #45 Is there anything left TODO? If so please detail and reopen.
I'm closing this for now
Thanks
