### ISSUE TITLE
Project color

### ISSUE THREAD

**Issue by gbalcewicz** [uc-group/bear-it#25]
Add project color so the project will be identified quicker by the color code. Also prepare predefined palette color. By default the color will be selected randomly from it in creation view.

**Comment by pgoca** [comment]
If the task is still available then I can take it. Here's a simple drawing how I imagine this to look like.
!(Scheme)[https://i.imgur.com/CKMw1i0.png]

**Comment by pgoca** [comment]
Alrighty, I need to look over vuetify, I didn't know it is used in this project. Thanks :)
