### ISSUE TITLE
List component card/table

### ISSUE THREAD

**Issue by gbalcewicz** [uc-group/bear-it#31]
Introduce component for lists letting to display list as cards or table rows.

**Comment by mariuszniemiec** [comment]
Could you be more elaborate? Which lists are you referring?

**Comment by gbalcewicz** [comment]
This is just as a note for me but sure. So now we have list of tiles in the project list. I would like to have two types of view for the user to select i.e two buttons one will display this list as it is in tiles but selecting other will show this list as a table. This could be made in generic way. If you are interested in this you can look at https://vuejs.org/v2/guide/render-function.html#Functional-Components, there is a `smart-list` I was thinking something like that.

**Comment by pgoca** [comment]
I assigned this task to myself, @mariuszniemiec have you started (or planned to start) working on this task? Let me know if you want to work on it

**Comment by mariuszniemiec** [comment]
@pgoca thanks for notice, but it's fine. I'm sometimes asking questions when I feel like task description is not perfectly clear.
GLHF
