### ISSUE TITLE
500 error when trying to login with Github. (Cannot create user without name)

### ISSUE THREAD

**Issue by atokarczyk** [uc-group/bear-it#9]
![image](https://user-images.githubusercontent.com/10808956/65855535-6c4e9b80-e35f-11e9-84e7-98d05bce9dc7.png)

**Comment by gbalcewicz** [comment]
Thanks for reporting this. I'll check it.

**Comment by gbalcewicz** [comment]
It seems, that user has no name coming from github. Let's fix this by setting optional name, if not provided the name will be the same as username.
